### ISSUE TITLE
请问一下EXE文件无法执行是需要安装Python环境吗

### ISSUE THREAD

**Issue by boatt** [shiweibsw/Translation-Tools#1]
运行时弹出无法定位到程序输入点ucrbase.terminate于动态链接库api-ms等等提示 。。。。。。。。。。

**Comment by shiweibsw** [comment]
exe文件不用依赖python环境，特意找了一台没有安装python的PC试了一下，没有问题的，那个提示有可能是你的PC上缺少c++2015 环境，某些exe执行程序必须依赖这个，尝试重新安装Visual C++ 2015 ，还是不行的话建议安装python运行环境通过脚本执行导入导出
